/**
 * project-thumbs.ts
 *
 * Maps a full-resolution project image path to its thumbnail variant.
 *
 * Two families of source image exist, each with its own thumb convention:
 *
 * 1. Baked repo assets — 640px WebP generated by
 *      npm run projects:thumbs  (also runs automatically as prebuild)
 *    /images/projects-fb/<base>.<ext> → /images/projects-fb/thumbs/<base>.webp
 *
 * 2. CMS uploads — 480px sibling written at upload time by the upload router
 *    (packages/cms-rag/server/routes-upload.ts, `resize.thumbWidth`), same
 *    directory and extension, "-thumb" appended to the stem:
 *    /uploads/cms/<base>.png → /uploads/cms/<base>-thumb.png
 *
 *    These siblings were being generated but never requested, so admin-set
 *    covers loaded at full resolution — 1.8-3.0 MB PNGs against ~72 KB thumbs.
 *
 * Anything else is returned unchanged, so the helper stays safe to call on any
 * image path. /uploads/docs/ is deliberately NOT mapped: that mount has no
 * sharp post-processing and therefore no -thumb siblings.
 *
 * Every caller pairs this with a full-res onError/decode fallback, so a missing
 * variant (e.g. an upload predating the resize config) degrades to the original
 * rather than a broken image.
 */

const FB_PREFIX = "/images/projects-fb/";
const THUMB_PREFIX = "/images/projects-fb/thumbs/";
const CMS_UPLOAD_PREFIX = "/uploads/cms/";
const THUMB_SUFFIX = "-thumb";

/**
 * Returns the thumbnail path for a project image, or the original path for
 * anything without a known thumb convention.
 *
 * Example:
 *   toThumbPath("/images/projects-fb/abc.jpg")  // → "/images/projects-fb/thumbs/abc.webp"
 *   toThumbPath("/uploads/cms/20260725-ab.png") // → "/uploads/cms/20260725-ab-thumb.png"
 *   toThumbPath("/uploads/docs/spec.pdf")       // → "/uploads/docs/spec.pdf"  (unchanged)
 */
export function toThumbPath(fullPath: string): string {
  if (!fullPath) return fullPath;

  // CMS uploads: 480px "-thumb" sibling, same directory and extension.
  if (fullPath.startsWith(CMS_UPLOAD_PREFIX)) {
    const dotIdx = fullPath.lastIndexOf(".");
    // No extension — nothing to derive a sibling name from.
    if (dotIdx <= fullPath.lastIndexOf("/")) return fullPath;

    const stem = fullPath.slice(0, dotIdx);
    // Already a thumb; do not produce "-thumb-thumb".
    if (stem.endsWith(THUMB_SUFFIX)) return fullPath;

    return `${stem}${THUMB_SUFFIX}${fullPath.slice(dotIdx)}`;
  }

  if (!fullPath.startsWith(FB_PREFIX)) return fullPath;

  const filename = fullPath.slice(FB_PREFIX.length);
  // Skip if already inside the thumbs sub-directory.
  if (filename.startsWith("thumbs/")) return fullPath;

  // Strip existing extension, append .webp.
  const dotIdx = filename.lastIndexOf(".");
  const basename = dotIdx !== -1 ? filename.slice(0, dotIdx) : filename;
  return `${THUMB_PREFIX}${basename}.webp`;
}
