/**
 * project-thumbs.ts
 *
 * Maps a full-resolution project image path to its thumbnail variant.
 * Thumbnails are 640px-wide WebP files generated by:
 *   npm run projects:thumbs  (also runs automatically as prebuild)
 *
 * Source path format:  /images/projects-fb/<basename>.<ext>
 * Thumb path format:   /images/projects-fb/thumbs/<basename>.webp
 *
 * Only paths under /images/projects-fb/ are mapped; anything else is
 * returned unchanged so the helper is safe to call on any image path.
 */

const FB_PREFIX = "/images/projects-fb/";
const THUMB_PREFIX = "/images/projects-fb/thumbs/";

/**
 * Returns the thumbnail path for a project-fb image, or the original path
 * for anything outside that directory.
 *
 * Example:
 *   toThumbPath("/images/projects-fb/abc123.jpg") // → "/images/projects-fb/thumbs/abc123.webp"
 *   toThumbPath("/uploads/custom.jpg")            // → "/uploads/custom.jpg"  (unchanged)
 */
export function toThumbPath(fullPath: string): string {
  if (!fullPath || !fullPath.startsWith(FB_PREFIX)) return fullPath;

  const filename = fullPath.slice(FB_PREFIX.length);
  // Skip if already inside the thumbs sub-directory.
  if (filename.startsWith("thumbs/")) return fullPath;

  // Strip existing extension, append .webp.
  const dotIdx = filename.lastIndexOf(".");
  const basename = dotIdx !== -1 ? filename.slice(0, dotIdx) : filename;
  return `${THUMB_PREFIX}${basename}.webp`;
}
